# Generated by Django 5.1.4 on 2025-01-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
        ('doctor', '0003_remove_doctor_available_time_doctor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='appointment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime'),
        ),
    ]
